### ISSUE TITLE
[BUG]: potential bugs about oversampling

### ISSUE THREAD

**Issue by zsliu98** [apmastering/AP-Mastering-Compressor#2]
https://github.com/apmastering/AP-Mastering-Compressor/blob/4fd6fa0340449bb0df73b3c4253fb555335b5fe5/Source/PluginEditor.cpp#L130-L137

On the message thread, it calls the `setOversampling()` method:

https://github.com/apmastering/AP-Mastering-Compressor/blob/4fd6fa0340449bb0df73b3c4253fb555335b5fe5/Source/PluginProcessor.cpp#L127-L160

where several methods of `oversampling` are called. However, it is possible that the `oversampling` is currently used by the audio thread. Besides that, it seems that the old `oversampling` is not destroyed.

**Comment by apmastering** [comment]
excellent work. To be honest it was a real pain getting OS working, so my code there was sloppy. I've gone over it and done smart pointers instead, with mutex to prevent simultaneous OS type change whilst process block is running.

much cleaner now! Thanks!

**Comment by apmastering** [comment]
changes pushed
