### ISSUE TITLE
[BUG]: thread safety of meter values

### ISSUE THREAD

**Issue by zsliu98** [apmastering/AP-Mastering-Compressor#3]
https://github.com/apmastering/AP-Mastering-Compressor/blob/4fd6fa0340449bb0df73b3c4253fb555335b5fe5/Source/PluginEditor.cpp#L261-L262

It accesses the meter values on the message thread. However, the meter values are written on the audio thread. It is not thread-safe. Perhaps std::atomic would be a quick solution.

**Comment by apmastering** [comment]
Again, thanks a lot for the great observation. I was a bit unsure about this when I wrote it, but I figured that race conditions there would be practically irrelevant as it's just metering. But you are correct that this is lazy code. I'm going to change it after breakfast. Thanks!

**Comment by apmastering** [comment]
OK I've overhauled this and it should be solid now. Thanks for the bug report!
